name: Create and publish a nuget package
on:
  push:
    branches: ['master']
jobs:
  build-and-push-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v4
      - run: dotnet build
      - run: dotnet nuget push *.nupkg
